src/Directory.build.props, src/SignService/SignService.csproj
This removes the requirement of installing the net47 targeting pack, and adds the missing package reference for accessing the registry in .NET Core.
Fixes #199
=> Fix build breaks

docs/Administration.md
As suggested in issue #216, I've cobbled together something that describes how I got Sign Service working with a certificate in an existing Key Vault.
=> Add docs for working with existing Key Vaults

arm/ArmDeploy/azuredeploy.json
Fixes #264
Recently the Microsoft.ApplicationInsights.AzureWebSites resource was removed from the ARM template, but this dependency on it was not, causing a validation error with the template. This commit removes the old dependsOn clause.
=> Remove dependency on Application Insights resource

src/SignService/Utils/CryptoConfigShims.cs
Fixes #266
The previous code attempts to invoke an internal method in .NET Core as if it's non-generic, but in recent framework versions it _is_ generic and the invocation fails. This commit replaces the call with a non-reflective call on a public method to avoid similar backwards-breaking changes in the future.
I've tested this code, and it successfully signs a VSTO ClickOnce archive.
Note: There are some special cases handled by the internal method [System.Security.Cryptography.Xml.CryptoHelpers.CreateFromName](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/CryptoHelpers.cs) that are not handled by the replacement method, `CryptoConfig.CreateFromName` (they're explicitly listed in a switch in …
=> Avoid reflection in CryptoConfigShims

src/SignService/SigningTools/AzureSignToolSignService.cs, src/SignService/SigningTools/MageSignService.cs, src/SignService/SigningTools/NuGetSignService.cs, src/SignService/SigningTools/VsixSignService.cs
All signing methods perform 3 attempts to sign.
The retrying code looks like the intention is to start with a delay of 5 seconds and then increase the delay exponentially: 5s before attempt 2, 11.1s before attempt 3.
Because the increase happens before the first retry, the actual delay times are 11.1s before attempt 2 and 37.3s before attempt 3.
This change makes the actual behaviour match the assumed intention.
=> Change base retry delay to 5 sec

src/SignService/Startup.cs
As discussed in #356, the current behavior of SignService is to return 404 errors when deployed because it uses the default asp.net core error handling and the current Error action is missing a route attribute.
This PR simply remove the default UseExceptionHandler call, to let asp.net core return a raw 500 error when using the API. This will ease debugging when a problem occurs.
Fix #356
=> Remove service exception handler

src/SignClient/SignCommand.cs
This option is in fact required and will raise a NRE is not set.
This PR simply add a check like other required parameters.
=> SignClient: add --secret option check

src/SignService/SigningTools/AppInstallerService.cs
This PR adds logic for finding the tag with the `Publisher` attribute for `.appx` files which has a different element name to `.appxbundle` files.  
It does this via a simple `??` fallback if the `appxbundle` tag cannot be found.
=> Add fallback logic for appx tag

src/SignService/SigningTools/MageSignService.cs
Better error message when the manifest file is not found.
Fix #355.
=> Do not require .manifest file to be included in the filter to be signed.

.vsts-ci.yml
Resolve https://github.com/dotnet/sign/issues/439.
The .NET engineering team removed some VM's.  This PR replaces those obsolete VM's with equivalent VM's.
=> CLI:  fix CI build

Directory.Packages.props, src/Sign.Cli/Sign.Cli.csproj, src/Sign.Core/Sign.Core.csproj
Resolve https://github.com/dotnet/sign/issues/443.
This change updates package dependencies, mostly updating from a prerelease version of .NET 7 to its final .NET 7.0 version.  This change also uses `PrivateAssets` to prevent some dependencies from flowing unnecessarily to a referencing project.
Note:  this source branch is based on a target branch which currently has an open PR (https://github.com/dotnet/sign/pull/442).  The reason is because the cli branch build is currently broken and CI builds for PR's fail.  The current target branch has the fix.  Once the target branch merges into the cli branch, I will retarget this PR at the cli branch.
=> CLI:  update dependencies

src/Sign.Cli/Sign.Cli.csproj
Resolve https://github.com/dotnet/sign/issues/459.
This change adds redistributable Windows SDK tools and .NET Framework tools (mage.exe) to the NuGet package.  This is necessary because the CLI requires these local copies.  (They may not already exist on a machine.)
=> CLI:  add SDK tools to NuGet package

src/Sign.Cli/Sign.Cli.csproj
Resolve https://github.com/dotnet/sign/issues/465.
Currently, the only target platform is Windows x64, so these x86 tools are unused.
Note that mage.exe is an x86 tool that is still used.
=> CLI:  remove unused x86 tools

src/Sign.Core/Containers/ContainerProvider.cs, src/Sign.Core/SignatureProviders/ClickOnceSignatureProvider.cs, src/Sign.Core/SignatureProviders/NuGetSignatureProvider.cs, src/Sign.Core/SignatureProviders/RSAPKCS1SHA256SignatureDescription.cs, src/Sign.Core/SignatureProviders/RSAPKCS1SignatureDescription.cs, test/Sign.Core.Test/Containers/ContainerProviderTests.cs, test/Sign.Core.Test/SignatureProviders/AppInstallerServiceSignatureProviderTests.cs, test/Sign.Core.Test/SignatureProviders/AzureSignToolSignatureProviderTests.cs, test/Sign.Core.Test/SignatureProviders/ClickOnceSignatureProviderTests.cs, test/Sign.Core.Test/SignatureProviders/NuGetSignatureProviderTests.cs, test/Sign.Core.Test/SignatureProviders/VsixSignatureProviderTests.cs, test/Sign.Core.Test/TestInfrastructure/AggregatingSignatureProviderSpy.cs
Resolve https://github.com/dotnet/sign/issues/469.
This change fixes the 3 bugs described in the issue and adds unit tests and, in particular, one unit test which thoroughly verifies `ClickOnceSignatureProvider.SignAsync(...)` behavior.
Note that adding `.clickonce` file extension as a supported ZIP container extension follows current behavior in the existing SignService CLI but should be viewed as a temporary change.  For details see https://github.com/dotnet/sign/issues/470.
=> CLI:  fix bugs and add tests

src/Sign.Cli/Program.cs
Resolve https://github.com/dotnet/sign/issues/475.
The upcoming preview explicitly only supports Windows x64.  This change blocks x86 with a link to upvote support for it.
=> CLI:  block x86 with useful error message

.editorconfig, src/Sign.Core/FileList/Globber.cs
Resolve https://github.com/dotnet/sign/issues/450.
This change resolves 2 [CA1305](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1305) warnings and enables an analyzer to catch regressions.
Note that this code change has no runtime behavioral impact.  [`int.Parse(string)` uses `NumberFormatInfo.CurrentInfo` behind the scenes](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Int32.cs,134).
=> CLI:  fix CA1305

Directory.Build.props, src/Sign.Cli/Sign.Cli.csproj
Resolve https://github.com/dotnet/sign/issues/483.
This change adds https://github.com/dotnet/sign/blob/cli/THIRD-PARTY-NOTICES.txt to the root of the package.
=> CLI:  add 3rd party notices file to package

src/Sign.Cli/Sign.Cli.csproj
Resolve https://github.com/dotnet/sign/issues/496.
This change adds the license file to the root of the NuGet package.
=> CLI: add license to package

eng/Signing.props
Resolve https://github.com/dotnet/sign/issues/499.
All signable files must be signed.  In the case of already signed 3rd party files, we need to add a second (Microsoft 3rd party) signature.
=> CLI:  sign 3rd party libraries

eng/Signing.props
Resolve https://github.com/dotnet/sign/issues/499.
Previously, I missed NuGetKeyVaultSignTool.Core.dll in https://github.com/dotnet/sign/pull/500.
=> CLI:  3rd party sign NuGetKeyVaultSignTool.Core.dll

src/Sign.Core/Certificates/CertificateVerifier.cs, src/Sign.Core/Certificates/ICertificateVerifier.cs, src/Sign.Core/Resources.Designer.cs, src/Sign.Core/Resources.resx, src/Sign.Core/ServiceProvider.cs, src/Sign.Core/Signer.cs, test/Sign.Core.Test/Certificates/CertificateVerifierTests.cs, test/Sign.Core.Test/ServiceProviderTests.cs
Resolve https://github.com/dotnet/sign/issues/502.
If a certificate is not yet valid or is expired, a warning will display "The certificate is not time valid."
=> CLI: warn if certificate is not time valid

src/Sign.Cli/Sign.Cli.csproj, src/Sign.Cli/SignCommand.cs
Resolve https://github.com/dotnet/sign/issues/510.
This change updates the tool's name from ".NET Sign CLI" to simply "Sign CLI".
=> Update tool name from ".NET Sign CLI" to "Sign CLI"

global.json
Resolve https://github.com/dotnet/sign/issues/509.
This change updates the .NET 7 SDK version used from pre-GA preview to GA.  It also updates the Arcade SDK version.
=> Update .NET and Arcade SDK's

.vsts-ci.yml
Resolve https://github.com/dotnet/sign/issues/513.
This change fixes the internal build by using a newer VM image with VS 2022 instead of VS 2019.
=> CI: update build machine image to support .NET 7.0.100 SDK

scripts/VerifyNuGetPackage.ps1, src/Sign.Cli/Sign.Cli.csproj
Resolve https://github.com/dotnet/sign/issues/525.
This change fixes a bug where Windows SDK tools were not included in the NuGet package.  The root problem is that the NuGet packages directory is different between `dotnet restore` and an Arcade `eng\common\CIBuild.cmd`; [Arcade installs packages to a .packages directory in the repository's root directory](https://github.com/dotnet/arcade/blob/6ef9e132005430f2920e0c26128bf9ba15c7644e/eng/common/tools.sh#L324).  NuGet pack could not find the Windows SDK package because it was looking in the wrong packages directory.
This change also adds pack verification to the CI build to ensure this does not regress.
=> Add SDK tools to NuGet package

Directory.Packages.props, src/Sign.Cli/Sign.Cli.csproj
Resolve https://github.com/dotnet/sign/issues/527.
This change does a few things:
- Uses the latest release version of the Microsoft.Windows.SDK.BuildTools package.  Release versions are signed with trusted certificates, whereas preview versions are not.
- Updates (and simplifies) how the Sign.Cli project copies SDK files.  This was necessary because if Visual Studio is installed, a package in a shared Visual Studio NuGet fallback folder is referenced, and there isn't a great way to get the SDK tool file paths (for copying) later.  Pulling in the package's build assets vastly simplifies everything.
- Fixes internal CI build failures.
=> Update Windows SDK

src/Sign.Cli/Program.cs, src/Sign.Core/FileSystem/AppRootDirectoryLocator.cs, src/Sign.Core/FileSystem/IAppRootDirectoryLocator.cs, src/Sign.Core/ServiceProvider.cs, src/Sign.Core/Tools/ToolConfigurationProvider.cs, test/Sign.Core.Test/FileSystem/AppRootDirectoryLocatorTests.cs, test/Sign.Core.Test/ServiceProviderTests.cs, test/Sign.Core.Test/Tools/ToolConfigurationProviderTests.cs
Resolve https://github.com/dotnet/sign/issues/531.
The issue is that the CLI currently uses `Environment.ProcessPath` to deduce the location of SDK tools.  However, when installed as a .NET global tool, the SDK tools directory is relative to a different directory, where the NuGet package is extracted.
This change uses a consistent way of obtaining the SDK tools directory by basing it on the location of Sign.Core.dll.
=> Fix discovery of package content

src/Sign.Cli/AzureKeyVaultCommand.cs, src/Sign.Cli/CodeCommand.cs, src/Sign.Core/ISigner.cs, src/Sign.Core/SignatureProviders/SignOptions.cs, src/Sign.Core/Signer.cs, test/Sign.Cli.Test/CodeCommandTests.cs, test/Sign.Cli.Test/Options/TimestampUrlOptionTests.cs, test/Sign.Cli.Test/Options/UriOptionTests.cs, test/Sign.Cli.Test/SignCommandTests.cs, test/Sign.Core.Test/SignatureProviders/AggregatingSignatureProviderTests.cs, test/Sign.Core.Test/SignatureProviders/ClickOnceSignatureProviderTests.cs, test/Sign.Core.Test/SignatureProviders/DefaultSignatureProviderTests.cs
Resolve https://github.com/dotnet/sign/issues/538.
This change makes timestamping required.
=> Require timestamping for signing

Directory.Packages.props
Resolve https://github.com/dotnet/sign/issues/545.
This change updates AzureSign.Core from 3.0.0 to 4.0.1.
=> Update AzureSign.Core from 3.0.0 to 4.0.1

Directory.Packages.props, src/Sign.Core/Sign.Core.csproj
Resolve https://github.com/dotnet/sign/issues/555.
This change brings in version 6.4.0 of NuGet dependencies instead of 6.0.0-preview.4.243.
=> Update NuGet.* dependencies

test/Sign.Cli.Test/Options/BaseDirectoryOptionTests.cs, test/Sign.Cli.Test/Options/DescriptionOptionTests.cs, test/Sign.Cli.Test/Options/DescriptionUrlOptionTests.cs, test/Sign.Cli.Test/Options/DirectoryInfoOptionTests.cs, test/Sign.Cli.Test/Options/FileDigestOptionTests.cs, test/Sign.Cli.Test/Options/HashAlgorithmNameOptionTests.cs, test/Sign.Cli.Test/Options/Int32OptionTests.cs, test/Sign.Cli.Test/Options/MaxConcurrencyOptionTests.cs, test/Sign.Cli.Test/Options/OptionTests.cs, test/Sign.Cli.Test/Options/OutputOptionTests.cs, test/Sign.Cli.Test/Options/PublisherNameOptionTests.cs, test/Sign.Cli.Test/Options/TimestampDigestOptionTests.cs, test/Sign.Cli.Test/Options/TimestampUrlOptionTests.cs, test/Sign.Cli.Test/Options/UriOptionTests.cs, test/Sign.Cli.Test/Options/VerbosityOptionTests.cs
Resolve https://github.com/dotnet/sign/issues/544.
This change simplifies tests a bit and checks error messages.
CC @erdembayar, @clairernovotny
=> Test:  improve tests by checking error messages

Directory.Packages.props, src/Sign.Core/KeyVault/KeyVaultService.cs, src/Sign.Core/Resources.Designer.cs, src/Sign.Core/Resources.resx, src/Sign.Core/ServiceProvider.cs, src/Sign.Core/Sign.Core.csproj, src/Sign.Core/Signer.cs, test/Sign.Core.Test/SignerTests.cs
Resolve https://github.com/dotnet/sign/issues/579.
This change:
* wires up the `-v` | `--verbosity` option to enable logging verbosity
* taps into Microsoft.Extensions.Logging's configuration options to enable setting logging options (e.g.:  verbosity, format, etc.) via environment variables or appsettings.json file
* cleans up some code to use dependency injection
* adds logging for certificate retrieval
* adds some unit tests
=> Fix and improve logging

src/Sign.Core/Containers/ContainerProvider.cs, src/Sign.Core/Containers/IContainerProvider.cs, src/Sign.Core/Containers/NuGetContainer.cs, src/Sign.Core/Containers/ZipContainer.cs, src/Sign.Core/SignatureProviders/AggregatingSignatureProvider.cs, test/Sign.Core.Test/Containers/ContainerProviderTests.cs, test/Sign.Core.Test/Containers/NuGetContainerTests.cs, test/Sign.Core.Test/TestInfrastructure/AggregatingSignatureProviderTest.cs, test/Sign.Core.Test/TestInfrastructure/ContainerProviderStub.cs, test/Sign.Core.Test/TestInfrastructure/DirectoryServiceStub.cs
Resolve https://github.com/dotnet/sign/issues/547.
This change enables signing an already signed NuGet package.
=> Enable signing already signed NuGet package

src/Sign.Cli/AzureKeyVaultCommand.cs, src/Sign.Core/ServiceProvider.cs, test/Sign.Core.Test/ServiceProviderTests.cs
Resolve https://github.com/dotnet/sign/issues/579.
This change fixes the `-v` | `--verbosity` option once and for all and adds unit test coverage too.
=> Fix verbosity option

Directory.Packages.props
This change uses an explicit version instead of an Arcade property for the System.CommandLine package.
Note that the [package version isn't changing](https://github.com/dotnet/sign/blob/25b85a1dba230b6ed59d9cf66704a06ddbe430a1/eng/Versions.props#L36).
=> Use explicit version instead of property for package version

src/Sign.Cli/AzureKeyVaultCommand.cs, src/Sign.Cli/CodeCommand.cs, src/Sign.Cli/Resources.Designer.cs, src/Sign.Cli/Resources.resx, src/Sign.Cli/xlf/Resources.cs.xlf, src/Sign.Cli/xlf/Resources.de.xlf, src/Sign.Cli/xlf/Resources.es.xlf, src/Sign.Cli/xlf/Resources.fr.xlf, src/Sign.Cli/xlf/Resources.it.xlf, src/Sign.Cli/xlf/Resources.ja.xlf, src/Sign.Cli/xlf/Resources.ko.xlf, src/Sign.Cli/xlf/Resources.pl.xlf, src/Sign.Cli/xlf/Resources.pt-BR.xlf, src/Sign.Cli/xlf/Resources.ru.xlf, src/Sign.Cli/xlf/Resources.tr.xlf, src/Sign.Cli/xlf/Resources.zh-Hans.xlf, src/Sign.Cli/xlf/Resources.zh-Hant.xlf, src/Sign.Core/ISigner.cs, src/Sign.Core/SignatureProviders/ClickOnceSignatureProvider.cs, src/Sign.Core/SignatureProviders/SignOptions.cs, src/Sign.Core/Signer.cs, test/Sign.Cli.Test/Options/ApplicationNameOptionTests.cs, test/Sign.Cli.Test/Options/DeploymentNameOptionTests.cs, test/Sign.Core.Test/SignatureProviders/ClickOnceSignatureProviderTests.cs
Resolve https://github.com/dotnet/sign/issues/567.
This change renames the existing `-pn` | `--publisher-name` option to `-dn` | `--deployment-name`.  This option was already setting the deployment name.  Also, this change introduces a new `-pn` | `--publisher-name` option for setting publisher name. 
=> Enable setting the publisher name and change old `--publisher-name` option to `--application-name`

src/Sign.Cli/Resources.Designer.cs, src/Sign.Cli/Resources.resx, src/Sign.Cli/xlf/Resources.cs.xlf, src/Sign.Cli/xlf/Resources.de.xlf, src/Sign.Cli/xlf/Resources.es.xlf, src/Sign.Cli/xlf/Resources.fr.xlf, src/Sign.Cli/xlf/Resources.it.xlf, src/Sign.Cli/xlf/Resources.ja.xlf, src/Sign.Cli/xlf/Resources.ko.xlf, src/Sign.Cli/xlf/Resources.pl.xlf, src/Sign.Cli/xlf/Resources.pt-BR.xlf, src/Sign.Cli/xlf/Resources.ru.xlf, src/Sign.Cli/xlf/Resources.tr.xlf, src/Sign.Cli/xlf/Resources.zh-Hans.xlf, src/Sign.Cli/xlf/Resources.zh-Hant.xlf
Resolve https://github.com/dotnet/sign/issues/559.
This change updates the description for `--verbosity` option to display the correct allowed values.
=> Update verbosity description

Directory.Packages.props, src/Sign.Core/Sign.Core.csproj
Resolve https://github.com/dotnet/sign/issues/539.
This change updates from System.Security.Cryptography.Pkcs 7.0 to 7.0.1, which brings in [this fix](https://github.com/dotnet/runtime/pull/80188).
I've manually verified that this works.  It's difficult to satisfactorily automate testing of this scenario, so I've created https://github.com/dotnet/sign/issues/595 as a separate task.
=> Update to System.Security.Cryptography.Pkcs 7.0.1

src/Sign.Cli/Resources.Designer.cs, src/Sign.Cli/Resources.resx
Resolve https://github.com/dotnet/sign/issues/599.
This change removes a duplicate message about the default value for the `-m` | `--max-concurrency` option.
```
-m, --max-concurrency <max-concurrency>                Maximum concurrency. [default: 4]
```
=> Remove duplicate default value from help

src/Sign.Cli/AzureKeyVaultCommand.cs, src/Sign.Cli/CodeCommand.cs, test/Sign.Cli.Test/CodeCommandTests.cs, test/Sign.Cli.Test/Options/TimestampUrlOptionTests.cs, test/Sign.Cli.Test/Options/UriOptionTests.cs
Resolve https://github.com/dotnet/sign/issues/597.
This change makes Azure Code Signing timestamping service the default.  The default can be overridden with the `-t` | `--timestamp-url` option.
Note that changing `IsRequired` from `true` to `false` means that a user isn't required to pass the option.  The new default value guarantees that there will be a value, so timestamping is still effectively required.
=> Make ACS the default timestamping service

src/Sign.Core/Resources.Designer.cs, src/Sign.Core/Resources.resx, src/Sign.Core/xlf/Resources.cs.xlf, src/Sign.Core/xlf/Resources.de.xlf, src/Sign.Core/xlf/Resources.es.xlf, src/Sign.Core/xlf/Resources.fr.xlf, src/Sign.Core/xlf/Resources.it.xlf, src/Sign.Core/xlf/Resources.ja.xlf, src/Sign.Core/xlf/Resources.ko.xlf, src/Sign.Core/xlf/Resources.pl.xlf, src/Sign.Core/xlf/Resources.pt-BR.xlf, src/Sign.Core/xlf/Resources.ru.xlf, src/Sign.Core/xlf/Resources.tr.xlf, src/Sign.Core/xlf/Resources.zh-Hans.xlf, src/Sign.Core/xlf/Resources.zh-Hant.xlf
Resolve https://github.com/dotnet/sign/issues/564.
This change removes the input file path from the successful completion message so that the completion message is more general:  Completed in _x_ ms.
=> Make successful completion message more generic 

src/Sign.Cli/Sign.Cli.csproj
Resolve https://github.com/dotnet/sign/issues/566.
Add the repository's README.md to the NuGet package root.
=> Add README.md to NuGet package

src/Sign.Core/Signer.cs, test/Sign.Core.Test/SignerTests.cs, test/Sign.Core.Test/TestInfrastructure/TestLogEntry.cs, test/Sign.Core.Test/TestInfrastructure/TestLogger.cs
Resolve https://github.com/dotnet/sign/issues/636.
https://github.com/dotnet/sign/pull/611 made the completion message more generic, mainly by removing the file path.  However, the change introduced a regression:  by not also removing the file path format string argument, the file path still displayed, but the completion time did not.
This change removes the file path format string argument and adds tests.
=> Fix completion message

global.json
The [previous attempt](https://github.com/dotnet/sign/pull/669) to fix internal build didn't bring in the required version of MSBuild.
This PR brings in MSBuild version 17.8.5 when >=17.8.3 is required.
=> Update MSBuild to 17.8.5

.vsts-ci.yml, eng/PoliCheckExclusions.xml
The last internal build had generated some PoliCheck warnings for strings in the .NET SDK directory.  We should ignore these as part of our builds.
=> Add .NET SDK directory as PoliCheck exclusion

.vsts-pr.yml
Progress on https://github.com/dotnet/sign/issues/676.
This PR simplifies the public CI pipeline YAML by removing stuff that only belongs in official builds.
=> CI:  simplify public CI YAML

.vsts-ci.yml
This PR migrates the official (internal) pipeline to 1ES.
(Note that this may actually break the official pipeline, but I'll have to work through it with a follow-up PR.)
=> CI:  migrate official pipeline to 1ES

.vsts-ci.yml
Progress on https://github.com/dotnet/sign/issues/676.
This PR pulls in the definition for the `DncEngInternalBuildPool` variable.
=> CI:  fix undefined variable

src/Sign.Cli/AzureKeyVaultCommand.cs, src/Sign.Cli/CertificateStoreCommand.cs, src/Sign.Cli/StandardStreamWriterExtensions.cs
This avoids the code duplication of the FormatMessage method. This is a first step in removing some of the duplication of the `AzureKeyVaultCommand` and `CertificateStoreCommand` that is also needed by a new `TrustedSigningCommand`.
=> Added extension method that replaces FormatMessage in the two command classes.

sign.sln, src/Sign.Cli/CertificateStoreCommand.cs, src/Sign.Cli/Sign.Cli.csproj, src/Sign.Core/Sign.Core.csproj, src/Sign.SignatureProviders.CertificateStore/CertificateStoreService.cs, src/Sign.SignatureProviders.CertificateStore/CertificateStoreServiceProvider.cs, src/Sign.SignatureProviders.CertificateStore/Sign.SignatureProviders.CertificateStore.csproj, test/Sign.SignatureProviders.CertificateStore.Test/CertificateStoreServiceProviderTests.cs, test/Sign.SignatureProviders.CertificateStore.Test/CertificateStoreServiceTests.cs, test/Sign.SignatureProviders.CertificateStore.Test/Sign.SignatureProviders.CertificateStore.Test.csproj, test/Sign.SignatureProviders.CertificateStore.Test/Usings.cs
This is a followup of the PR that moved the KeyVaultService and KeyVaultServiceProvider to their own library. This moves CertificateStoreService and CertificateStoreServiceProvider to their own library.
This PR also adds some unit tests for both classes.
=> Moved the CertificateStore services to their own library.

src/Sign.Cli/AzureKeyVaultCommand.cs, src/Sign.Cli/CertificateStoreCommand.cs, src/Sign.Cli/CodeCommand.cs, src/Sign.Core/ISignatureProvider.cs, src/Sign.SignatureProviders.CertificateStore/CertificateStoreServiceProvider.cs, src/Sign.SignatureProviders.KeyVault/KeyVaultServiceProvider.cs
This PR moves the shared logic of the AzureKeyVaultCommand and CertificateStoreCommand to a new Handle method inside the CodeCommand. And this also introduces a new interface called ISignatureProvider that can be used for a new TrustedSigningServiceProvider class.
=> Moved the shared logic of the AzureKeyVaultCommand and CertificateStoreCommand to a new Handle method inside the CodeCommand

test/Sign.SignatureProviders.CertificateStore.Test/CertificateStoreServiceProviderTests.cs, test/Sign.SignatureProviders.KeyVault.Test/KeyVaultServiceProviderTests.cs
This PR fixes a mistake that I made in my earlier pull request. I did not take in account that List.Add is not thread safe. Using a ConcurrentBag instead fixes this issue.
=> Use ConcurrentBag instead of a List because the .Add method of List is not thread safe.

src/Sign.Cli/AzureCredentialOptions.cs, src/Sign.Cli/AzureCredentialType.cs, src/Sign.Cli/Resources.Designer.cs, src/Sign.Cli/Resources.resx, src/Sign.Cli/xlf/Resources.cs.xlf, src/Sign.Cli/xlf/Resources.de.xlf, src/Sign.Cli/xlf/Resources.es.xlf, src/Sign.Cli/xlf/Resources.fr.xlf, src/Sign.Cli/xlf/Resources.it.xlf, src/Sign.Cli/xlf/Resources.ja.xlf, src/Sign.Cli/xlf/Resources.ko.xlf, src/Sign.Cli/xlf/Resources.pl.xlf, src/Sign.Cli/xlf/Resources.pt-BR.xlf, src/Sign.Cli/xlf/Resources.ru.xlf, src/Sign.Cli/xlf/Resources.tr.xlf, src/Sign.Cli/xlf/Resources.zh-Hans.xlf, src/Sign.Cli/xlf/Resources.zh-Hant.xlf, test/Sign.Cli.Test/AzureCredentialOptionsTests.cs
This pull requests adds the `--azure-credential-type` option that was discussed in #724. The easiest to start with was `environment` but it is build so we can add
=> Added --azure-credential-type that can be used to specify which Azure credential type should be enabled.

src/Sign.Cli/AzureCredentialOptions.cs, src/Sign.Cli/AzureCredentialType.cs, test/Sign.Cli.Test/AzureCredentialOptionsTests.cs
This PR adds `azure-cli` as a credential type. Having this options results in small speedup improvement because only the  `AzureCliCredential` type will be used by `DefaultAzureCredential`.  Being able to specify this credential type will be useful when `az login` is used in a pipeline.
=> Added azure-cli credential type.

src/Sign.Cli/AzureCredentialOptions.cs, src/Sign.Cli/Resources.Designer.cs, src/Sign.Cli/Resources.resx, src/Sign.Cli/xlf/Resources.cs.xlf, src/Sign.Cli/xlf/Resources.de.xlf, src/Sign.Cli/xlf/Resources.es.xlf, src/Sign.Cli/xlf/Resources.fr.xlf, src/Sign.Cli/xlf/Resources.it.xlf, src/Sign.Cli/xlf/Resources.ja.xlf, src/Sign.Cli/xlf/Resources.ko.xlf, src/Sign.Cli/xlf/Resources.pl.xlf, src/Sign.Cli/xlf/Resources.pt-BR.xlf, src/Sign.Cli/xlf/Resources.ru.xlf, src/Sign.Cli/xlf/Resources.tr.xlf, src/Sign.Cli/xlf/Resources.zh-Hans.xlf, src/Sign.Cli/xlf/Resources.zh-Hant.xlf, test/Sign.Cli.Test/AzureCredentialOptionsTests.cs
This PR makes all the `--azure-key-vault` obsolete and hidden. When the options are hidden they can still be used but they will no longer show up in the help. And this PR also introduces an option to set the `TenantId` property of the `DefaultAzureCredential`.
=> Added --azure-tenant-id option and made all the --azure-key-vault options obsolete.

src/Sign.Cli/AzureCredentialOptions.cs, src/Sign.Cli/AzureCredentialType.cs, src/Sign.Cli/Resources.Designer.cs, src/Sign.Cli/Resources.resx, src/Sign.Cli/xlf/Resources.cs.xlf, src/Sign.Cli/xlf/Resources.de.xlf, src/Sign.Cli/xlf/Resources.es.xlf, src/Sign.Cli/xlf/Resources.fr.xlf, src/Sign.Cli/xlf/Resources.it.xlf, src/Sign.Cli/xlf/Resources.ja.xlf, src/Sign.Cli/xlf/Resources.ko.xlf, src/Sign.Cli/xlf/Resources.pl.xlf, src/Sign.Cli/xlf/Resources.pt-BR.xlf, src/Sign.Cli/xlf/Resources.ru.xlf, src/Sign.Cli/xlf/Resources.tr.xlf, src/Sign.Cli/xlf/Resources.zh-Hans.xlf, src/Sign.Cli/xlf/Resources.zh-Hant.xlf, test/Sign.Cli.Test/AzureCredentialOptionsTests.cs
This PR adds the managed-identity credential type. This also adds two new option that are specific for a managed identity in the `DefaultAzureCredentialOptions`. I can take those out if the team thinks that it is too early to add those.
=> Added managed-identity credential type.

src/Sign.Core/Native/mansign2.cs, test/Sign.Core.Test/Native/SignedCmiManifest2Tests.cs
This PR fixes the issue that was reported in #735. There was an explicit cast to `RSAKeyVault` but this can be changed to `RSA` instead. I have updated a unit test to hit this "new" path and also removed an unnecessary duplicate check.
=> Fix ClickOnce signing using Trusted Signing

src/Sign.SignatureProviders.KeyVault/Sign.SignatureProviders.KeyVault.csproj
Resolve https://github.com/dotnet/sign/issues/748.
This change uses the version ([1.42.0](https://github.com/dotnet/sign/blob/1786400add5fabcb7135c4213637b47080bb1bc5/Directory.Packages.props#L8)) of Azure.Core that is defined in Directory.Packages.props to override the version RSAKeyVaultProvider brings in.  This should resolve a CG alert.
=> Resolve CG alert

Directory.Packages.props, THIRD-PARTY-NOTICES.txt, src/Sign.Core/Sign.Core.csproj, src/Sign.Core/Tools/NuGet/NuGetLogger.cs, src/Sign.Core/Tools/NuGet/NuGetPackageSigner.cs, src/Sign.Core/Tools/NuGet/NuGetSignatureProvider.cs, src/Sign.Core/Tools/NuGetSignTool.cs, src/Sign.SignatureProviders.KeyVault/KeyVaultService.cs, src/Sign.SignatureProviders.KeyVault/Sign.SignatureProviders.KeyVault.csproj
Resolve https://github.com/dotnet/sign/issues/649
This change:
* uses Azure Key Vault SDK's [`RSA`](https://learn.microsoft.com/dotnet/api/system.security.cryptography.rsa?view=net-8.0) implementation instead of RSAKeyVaultProvider's
* copies and modifies code from https://github.com/novotnyllc/NuGetKeyVaultSignTool/tree/946e5c863a12a65feceecce50840dc611d9d1da8/NuGetKeyVaultSignTool.Core to use the Azure Key Vault RSA implementation
* removes NuGetKeyVaultSignTool.Core and RSAKeyVaultProvider package dependencies
=> Use Azure Key Vault's RSA implementation

src/Sign.SignatureProviders.KeyVault/KeyVaultService.cs, src/Sign.SignatureProviders.KeyVault/KeyVaultServiceProvider.cs, test/Sign.SignatureProviders.KeyVault.Test/KeyVaultServiceTests.cs
This corrects the implementation of the creation of the CryptographyClient. The `KeyClient` that was created used the `KeyId` instead of the url of the keyvault here: `KeyClient keyClient = new(certificateWithPolicy.KeyId, _tokenCredential);`. And that was then used to create a `CryptographyClient` with an incorrect url.
I have fixed this by creating the `CryptographyClient` without using the `KeyClient` because we already get this information when the public key is retrieved. I have also removed the `_task` field to make it possible to pass the `cancellationToken` to the `GetCertificateAsync` call.
=> Correct creation of the CryptographyClient in the KeyVaultService.

README.md
See https://github.com/dotnet/sign/issues/753 for details.
This PR updates documentation to include another `Get` permission required for Key Vault usage.
=> Docs:  update Key Vault permissions

src/Sign.Cli/CertificateStoreCommand.cs, src/Sign.Cli/CertificateStoreResources.Designer.cs, src/Sign.Cli/CertificateStoreResources.resx, src/Sign.Cli/xlf/CertificateStoreResources.cs.xlf, src/Sign.Cli/xlf/CertificateStoreResources.de.xlf, src/Sign.Cli/xlf/CertificateStoreResources.es.xlf, src/Sign.Cli/xlf/CertificateStoreResources.fr.xlf, src/Sign.Cli/xlf/CertificateStoreResources.it.xlf, src/Sign.Cli/xlf/CertificateStoreResources.ja.xlf, src/Sign.Cli/xlf/CertificateStoreResources.ko.xlf, src/Sign.Cli/xlf/CertificateStoreResources.pl.xlf, src/Sign.Cli/xlf/CertificateStoreResources.pt-BR.xlf, src/Sign.Cli/xlf/CertificateStoreResources.ru.xlf, src/Sign.Cli/xlf/CertificateStoreResources.tr.xlf, src/Sign.Cli/xlf/CertificateStoreResources.zh-Hans.xlf, src/Sign.Cli/xlf/CertificateStoreResources.zh-Hant.xlf, src/Sign.SignatureProviders.CertificateStore/CertificateStoreService.cs, src/Sign.SignatureProviders.CertificateStore/CertificateStoreServiceProvider.cs, test/Sign.SignatureProviders.CertificateStore.Test/CertificateStoreServiceProviderTests.cs, test/Sign.SignatureProviders.CertificateStore.Test/CertificateStoreServiceTests.cs
Sign needs to be able to use user-protected keys, such as keys stored in a USB eToken device. These generally require user interaction when the key is used and signing will fail when dialogs are blocked.
User interaction requires the 'Silent' flag to not be set in CertificateStoreService.GetRsaAsync method. The rest of this is plumbing to make a user option available to this code.
The new option is --user-protected-key/-upk to turn off the silent flag. The flag name corresponds to the enum value
CspProviderFlags.UseUserProtectedKey in
System.Security.Cryptography. I preferred this to not-silent or -silent false (with a true default).
I'm sure there is a process for translation, but I do not know if this is done with the initial pull request.
=> Enable user protected keys in certificate store

README.md, src/Sign.Cli/PACKAGE.md, src/Sign.Cli/Program.cs, src/Sign.Cli/Resources.Designer.cs, src/Sign.Cli/Resources.resx, src/Sign.Cli/xlf/Resources.cs.xlf, src/Sign.Cli/xlf/Resources.de.xlf, src/Sign.Cli/xlf/Resources.es.xlf, src/Sign.Cli/xlf/Resources.fr.xlf, src/Sign.Cli/xlf/Resources.it.xlf, src/Sign.Cli/xlf/Resources.ja.xlf, src/Sign.Cli/xlf/Resources.ko.xlf, src/Sign.Cli/xlf/Resources.pl.xlf, src/Sign.Cli/xlf/Resources.pt-BR.xlf, src/Sign.Cli/xlf/Resources.ru.xlf, src/Sign.Cli/xlf/Resources.tr.xlf, src/Sign.Cli/xlf/Resources.zh-Hans.xlf, src/Sign.Cli/xlf/Resources.zh-Hant.xlf
Address https://github.com/dotnet/sign/issues/684
This change warns if MSVCRT 14 is not installed and updates documentation prerequisites.
=> Warn if MSVCRT 14 not detected

README.md, triage-policy.md
This PR adds triage policy documentation.
At some point, we should look into automating some of these steps with a bot, but for now this is all manual.
=> Add triage policy

test/Sign.Core.Test/AssemblyInitializer.cs, test/Sign.Core.Test/TestInfrastructure/Server/CertificateAuthority.cs, test/Sign.TestInfrastructure/Constants.cs, test/Sign.TestInfrastructure/EphemeralTrust.cs, test/Sign.TestInfrastructure/ResidualTestCertificatesFoundInRootStoreException.cs, test/Sign.TestInfrastructure/SelfIssuedCertificateCreator.cs, test/Sign.TestInfrastructure/TrustedCertificateFixture.cs
Resolve https://github.com/dotnet/sign/issues/786.
During normal test execution, some tests may add test certificates to the root store and remove them during cleanup.  However, if the cleanup doesn't execute normally --- say, the test execution process crashed ---, test certificates would still be in the root store.
This change looks for residual test certificates in the root store at the start of test execution.
* If no certificates were found, we'll resume test execution.
* If certificates were found and the process is elevated, we'll remove the certificates and resume execution.
* If certificates were found and the process is not elevated, we'll report this as an error and fail execution.
=> Test:  remove residual test certificates in root store at start of test run

global.json
Resolve https://github.com/dotnet/sign/issues/790
This change attempts to fix a build break that only reproes in the CI.
=> CI:  fix builds

test/Sign.TestInfrastructure/EphemeralTrust.cs
Resolve https://github.com/dotnet/sign/issues/792
This change suppresses a CodeQL warning for internal bug 2292291.
=> Test:  suppress CodeQL warning

global.json
Resolve https://github.com/dotnet/sign/issues/802.
This change should resolve Component Governance alerts.
See https://github.com/dotnet/msbuild/commit/977f965b0e18488a0768da26277177524f6d1107 for reference.
=> CI:  update xcopy-msbuild version

src/Sign.Core/Tools/VsixSignTool/SigningContext.cs, test/Sign.Core.Test/TestInfrastructure/CertificateStoreServiceStub.cs, test/Sign.Core.Test/TestInfrastructure/KeyVaultServiceStub.cs, test/Sign.Core.Test/TestInfrastructure/Server/CertificateAuthority.cs, test/Sign.Core.Test/TestInfrastructure/Server/PfxFilesFixture.cs, test/Sign.Core.Test/TestInfrastructure/Server/TimestampService.cs, test/Sign.TestInfrastructure/SelfIssuedCertificateCreator.cs
Resolve https://github.com/dotnet/sign/issues/812.
This change adds CodeQL suppressions for warnings that are tracked internally.
=> Add CodeQL suppressions

global.json
- Updated `xcopy-msbuild` in `global.json` to the latest available version on dotnet-eng
- Updated the dotnet 9 sdk references to the latest available version (these were out of sync)
- Updated the dotnet 8 runtime reference to the latest available version
I am raising this as I made the change to update xcopy-msbuild in [aspnetcore](https://github.com/dotnet/aspnetcore) via https://github.com/dotnet/aspnetcore/pull/60666 and spotted this repository was using the previous version also
=> Update global.json references to latest available versions

src/Sign.Cli/AzureKeyVaultCommand.cs
Resolve https://github.com/dotnet/sign/issues/827
https://github.com/dotnet/sign/pull/808 introduced a regression.
In Azure Key Vault:
* a Key Vault has a unique URI of the form:   `<scheme>://<authority>`
* a certificate has a unique URI of the form:  `<scheme>://<authority>/certificates/<certificateId>`
* a private key has a unique URI of the form:  `<scheme>://<authority>/keys/<certificateId>`
https://github.com/dotnet/sign/pull/808 added calls to [`CertificateClientBuilderExtensions.AddCertificateClient(...)`](https://learn.microsoft.com/dotnet/api/microsoft.extensions.azure.certificateclientbuilderextensions.addcertificateclient?view=azure-dotnet#microsoft-extensions-azure-certificateclientbuilderextensions-addcertificateclient-1(-0-system-uri)) and …
=> Azure Key Vault:  fix regression in Azure Key Vault signing

src/Sign.Cli/AzureKeyVaultCommand.cs
This removes the call to `KeyVaultKeyIdentifier.TryCreate` that we no longer need because of the fix that was done in #828.
=> Small cleanup as a follow up of #828

.editorconfig
While building the library today I suddenly got a build error due to CA2255 that mentions that we should not be using the ModuleInitializer attribute. This small patch updates the `.editorconfig` to silence that warning/error.
=> Silence CA2255 (The ModuleInitializer attribute should not be used in libraries) through the .editorconfig.

src/Sign.Core/DataFormatSigners/AppInstallerServiceSigner.cs, test/Sign.Core.Test/DataFormatSigners/AppInstallerServiceSignerTests.cs
Resolve https://github.com/dotnet/sign/issues/809.
This change adds support for all known App Installer namespaces (defined [here](https://learn.microsoft.com/uwp/schemas/appinstallerschema/app-installer-file#app-installer-file-versioning)).
=> MSIX:  support all App Installer namespaces

src/Sign.Core/Tools/VsixSignTool/Interop/Crypt32.cs, test/Sign.Core.Test/TestInfrastructure/Server/CertificatesFixture.cs, test/Sign.Core.Test/TestInfrastructure/Server/TimestampService.cs, test/Sign.Core.Test/Tools/VSIXSignTool/Crypt32Tests.cs, test/Sign.Core.Test/Tools/VSIXSignTool/OpcPackageSigningTests.cs
Progress on https://github.com/dotnet/sign/issues/671.
These 2 tests occasionally fail in CI runs but always succeed on rerun.  This change adds some additional logging to test output in the hopes that I'll be able to diagnose the issue when it happens again.
In short, this change modifies the test timestamp server to write details about every request and response to a file.  The tests append the contents of this file to the test output log.
The files are temporary and deleted after test execution.
CC @javierdlg
=> Test:  add diagnostic logging for some flaky timestamping tests

src/Sign.Core/Tools/VsixSignTool/XmlSignatureBuilder.cs, test/Sign.Core.Test/Tools/VSIXSignTool/OpcPackageSigningTests.cs
Resolve https://github.com/dotnet/sign/issues/837.
By default, `DateTimeOffset.ToString(string)` uses the current culture.  For en-DK, the time separator is `.` not `:`.  So, the result is a value which doesn't follow the [OPC signature timestamp format](https://learn.microsoft.com/windows/win32/api/msopc/ne-msopc-opc_signature_time_format).
This change forces the `DateTimeOffset.ToString(...)` call to use `CultureInfo.InvariantCulture`.  This produces the expected result regardless of the current culture.
=> VSIX:  fix signature timestamp format string bug

src/Sign.Cli/AzureKeyVaultCommand.cs, src/Sign.Core/DataFormatSigners/ClickOnceSigner.cs, src/Sign.Core/DataFormatSigners/SignOptions.cs, test/Sign.Cli.Test/SignCommandTests.Globbing.cs, test/Sign.Core.Test/DataFormatSigners/AggregatingSignerTests.Containers.cs, test/Sign.Core.Test/DataFormatSigners/AzureSignToolSignerTests.cs, test/Sign.Core.Test/DataFormatSigners/ClickOnceSignerTests.cs, test/Sign.Core.Test/DataFormatSigners/NuGetSignerTests.cs, test/Sign.Core.Test/DataFormatSigners/VsixSignerTests.cs, test/Sign.Core.Test/SignerTests.cs, test/Sign.Core.Test/TestInfrastructure/Server/PfxFilesFixture.cs
This change ensures that the `DirectoryService` is properly disposed of after use.  This ensures test files are deleted after test execution.
Also, some very minor reformatting changes.
Use https://github.com/dotnet/sign/pull/845/files?w=1 to ignore whitespace changes.
=> Test:  dispose DirectoryService

src/Sign.Core/DataFormatSigners/AzureSignToolSigner.cs, src/Sign.Core/DataFormatSigners/DynamicsBusinessCentralAppFileType.cs, src/Sign.Core/DataFormatSigners/ISignableFileType.cs, src/Sign.Core/DataFormatSigners/SignableFileTypeByExtension.cs, src/Sign.Core/Resources.Designer.cs, src/Sign.Core/Resources.resx, src/Sign.Core/xlf/Resources.cs.xlf, src/Sign.Core/xlf/Resources.de.xlf, src/Sign.Core/xlf/Resources.es.xlf, src/Sign.Core/xlf/Resources.fr.xlf, src/Sign.Core/xlf/Resources.it.xlf, src/Sign.Core/xlf/Resources.ja.xlf, src/Sign.Core/xlf/Resources.ko.xlf, src/Sign.Core/xlf/Resources.pl.xlf, src/Sign.Core/xlf/Resources.pt-BR.xlf, src/Sign.Core/xlf/Resources.ru.xlf, src/Sign.Core/xlf/Resources.tr.xlf, src/Sign.Core/xlf/Resources.zh-Hans.xlf, src/Sign.Core/xlf/Resources.zh-Hant.xlf, test/Sign.Core.Test/DataFormatSigners/AzureSignToolSignerTests.cs, test/Sign.Core.Test/DataFormatSigners/DynamicsBusinessCentralAppFileTypeTests.cs, test/Sign.Core.Test/DataFormatSigners/SignableFileTypeByExtensionTests.cs
Resolve https://github.com/dotnet/sign/issues/824.
https://github.com/dotnet/sign/pull/652 added support for signing Dynamics Business Central `.app` files, but the `.app` file extension is not exclusive to Dynamics Business Central apps.  In this bug, Sign CLI fails to sign a JSON file with an `.app` file extension.
This change updates Sign CLI to be smarter about detecting Dynamics Business Central `.app` files.  These files begin with a 4-byte header `4e 41 56 58` (NAVX), so we should only try signing if an `.app` file starts with this header.
CC @aholstrup1
=> Improve detection of Dynamics Business Central `.app` files

src/Sign.Cli/AzureKeyVaultCommand.cs, src/Sign.Cli/CertificateStoreCommand.cs, src/Sign.Cli/CodeCommand.cs, src/Sign.Cli/TrustedSigningCommand.cs, test/Sign.Cli.Test/SignCommandTests.cs
Fixes #815
The command documentation specifies that these commands take a "file(s)" parameter. They currently accept only a single argument, although it can be a glob to specify multiple files. This changes them to accept multiple filenames as separate arguments, similar to the existing behavior of signtool and azuresigntool.
=> Allow 'code' commands to accept multiple file arguments

src/Sign.SignatureProviders.TrustedSigning/RSATrustedSigning.cs, src/Sign.SignatureProviders.TrustedSigning/TrustedSigningService.cs
=> Fix bug where the RSA object that is created with GetRSAPublicKey is not disposed.

src/Sign.SignatureProviders.KeyVault/KeyVaultService.cs, src/Sign.SignatureProviders.KeyVault/RSAKeyVaultWrapper.cs
=> Added RSAKeyVaultWrapper that resolves calls to the ExportParameters method of the RSAKeyVault.

src/Sign.SignatureProviders.KeyVault/KeyVaultService.cs, src/Sign.SignatureProviders.KeyVault/RSAKeyVaultWrapper.cs, test/Sign.SignatureProviders.KeyVault.Test/KeyVaultServiceTests.cs
=> The KeyVaultService should use GetRSAPublicKey instead of GetRSAPrivateKey.

test/Sign.Core.Test/TestInfrastructure/Server/TimestampService.cs
Resolve https://github.com/dotnet/sign/issues/671
Recent test logging enhancements revealed that these 2 tests were interfering with each other by modifying a `HashSet<string>` collection concurrently.
This collection served no real purpose, so I'm removing it.
=> Test:  fix test bug

src/Sign.Cli/AzureCredentialOptions.cs, src/Sign.Cli/AzureCredentialType.cs, src/Sign.Cli/Resources.Designer.cs, src/Sign.Cli/Resources.resx, src/Sign.Cli/xlf/Resources.cs.xlf, src/Sign.Cli/xlf/Resources.de.xlf, src/Sign.Cli/xlf/Resources.es.xlf, src/Sign.Cli/xlf/Resources.fr.xlf, src/Sign.Cli/xlf/Resources.it.xlf, src/Sign.Cli/xlf/Resources.ja.xlf, src/Sign.Cli/xlf/Resources.ko.xlf, src/Sign.Cli/xlf/Resources.pl.xlf, src/Sign.Cli/xlf/Resources.pt-BR.xlf, src/Sign.Cli/xlf/Resources.ru.xlf, src/Sign.Cli/xlf/Resources.tr.xlf, src/Sign.Cli/xlf/Resources.zh-Hans.xlf, src/Sign.Cli/xlf/Resources.zh-Hant.xlf, test/Sign.Cli.Test/AzureCredentialOptionsTests.cs
=> Added --azure-credential-type option that can be used to specify the credential type for Azure authentication.

src/Sign.Cli/CertificateStoreResources.Designer.cs, src/Sign.Cli/CertificateStoreResources.resx, src/Sign.Cli/CodeCommand.cs, src/Sign.Cli/xlf/CertificateStoreResources.cs.xlf, src/Sign.Cli/xlf/CertificateStoreResources.de.xlf, src/Sign.Cli/xlf/CertificateStoreResources.es.xlf, src/Sign.Cli/xlf/CertificateStoreResources.fr.xlf, src/Sign.Cli/xlf/CertificateStoreResources.it.xlf, src/Sign.Cli/xlf/CertificateStoreResources.ja.xlf, src/Sign.Cli/xlf/CertificateStoreResources.ko.xlf, src/Sign.Cli/xlf/CertificateStoreResources.pl.xlf, src/Sign.Cli/xlf/CertificateStoreResources.pt-BR.xlf, src/Sign.Cli/xlf/CertificateStoreResources.ru.xlf, src/Sign.Cli/xlf/CertificateStoreResources.tr.xlf, src/Sign.Cli/xlf/CertificateStoreResources.zh-Hans.xlf, src/Sign.Cli/xlf/CertificateStoreResources.zh-Hant.xlf, src/Sign.Core/DataFormatSigners/AggregatingSigner.cs, src/Sign.Core/DataFormatSigners/SignOptions.cs, src/Sign.Core/ISigner.cs, src/Sign.Core/Signer.cs, test/Sign.Cli.Test/TestInfrastructure/SignerSpy.cs, test/Sign.Core.Test/DataFormatSigners/AggregatingSignerTests.Containers.cs, test/Sign.Core.Test/DataFormatSigners/AzureSignToolSignerTests.cs, test/Sign.Core.Test/DataFormatSigners/ClickOnceSignerTests.cs, test/Sign.Core.Test/DataFormatSigners/NuGetSignerTests.cs, test/Sign.Core.Test/DataFormatSigners/VsixSignerTests.cs, test/Sign.Core.Test/SignerTests.cs
Add a new `--recurse-containers`/`-rc` option that allows users to specify whether to sign the contents of container files recursively. 
This is enabled by default but can be disabled using `--recurse-containers=false`.
Disabling this feature will prevent sign tool from signing files in containers such as `appx` but will still sign the `appx` file itself. This is useful for those who sign their files before packaging them into a container.
Fixes #775
=> Add RecurseContainers option for signing process

NuGet.Config
Resolve https://github.com/dotnet/sign/issues/906.
After enabling package source mapping, the internal CI build has been unable to download a couple of .NET tools.
This change adds package source mappings for those tools.
=> CI:  add package source mappings for CI tools

docs/gh-build-and-sign.yml
While enabling signing for the [openai library](https://github.com/openai/openai-dotnet/pull/551) I hit a number of issues and so I'm contributing an update to the template here for what I ended up getting to work.
I'm guessing that the ADO template might need similar updates but I've not tested those, so I didn't want to update as part of this.
=> Update gh workflow signing sample
