dotnet/sign

src/SignService/Utils/TemporaryZipFile.cs
Adds support for using '!' in filter to exclude files.  Closes issue #27.
=> Adds support for excluding files in filter (Issue #27)

src/SignService/SignService.csproj
=> add probing for WinSDK path

src/SignService/SignService.csproj, src/SignService/SigningTools/VsixSignService.cs
This also accounts for some API surface changes.
=> Use public nuget package.

azure-pipelines.client.yml, azure-pipelines.server.yml, src/Directory.build.props, src/SignService/Program.cs, src/SignService/SignService.csproj, src/SignService/Startup.cs
This updates to ASP.NET Core 2.2.
Note that there's a bug in 2.2 that's causing lots of first-chance exceptions to be thrown:
https://github.com/dotnet/coreclr/issues/21743
=> Update to ASP.NET Core 2.2

src/SignService/Controllers/SignController.cs, src/SignService/SigningTools/SigningToolAggregate.cs, src/SignService/Utils/DirectoryUtility.cs
=> Cleaner temp file handling

src/SignService/Utils/DirectoryUtility.cs
Adding the allocations gave me a sleepless night
=> Reduce Task allocations for Async retries

README.md, src/SignClient/Globber.cs, src/SignClient/Program.cs, src/SignClient/SignCommand.cs, src/SignClient/appsettings.json
=> Add globbing support and concurrency.

azure-pipelines.client.yml, azure-pipelines.server.yml, src/InstallUtility/OptionalClaims.cs, src/SignService/Services/AdminService.cs, src/SignService/Utils/CoreContractResolver.cs
This resolves all warnings in the repo, and changes the pipeline to block introduction of new warnings in the future so we stay warning clean.
=> Fix compiler warnings

src/SignClient/SignCommand.cs
=> Return exit code 3 from SignClient when no files will be signed

azure-pipelines.server.yml, src/SignService/SigningTools/MageSignService.cs
Was an oversight from #34. Fixes #219.
=> Fix path to mage. 

src/SignClient/Program.cs, src/SignClient/SignCommand.cs
This may help to debug our MSAL issue. Tagging @clairernovotny who has context on the issue we're trying to figure out.
=> Enable logging of MSAL traces to aid in debugging.

.vsts-ci.yml
Set `DotNetPublishUsingPipelines` to `true` per [Arcade documentation](https://github.com/dotnet/arcade/blob/main/Documentation/CorePackages/Publishing.md).
Also, take advantage of [`${{ else }}`](https://learn.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-192-update#new-yaml-conditional-expressions) to simplify YAML logic.
=> CLI:  try to publish artifacts

src/Sign.Core/FileList/Globber.cs
Resolve https://github.com/dotnet/sign/issues/461.
=> CLI:  replace potentially offensive word

.vsts-ci.yml
Resolve https://github.com/dotnet/sign/issues/467.
=> CLI:  try to enable CodeQL

Directory.Build.props
Resolve https://github.com/dotnet/sign/issues/481.
This change enables [CheckForOverflowUnderflow](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/language#checkforoverflowunderflow) for all build configurations.
=> CLI:  enable CheckForOverflowUnderflow

Directory.Packages.props, THIRD-PARTY-NOTICES.txt
Resolve https://github.com/dotnet/sign/issues/484.
This change updates Azure.Identity from 1.7.0 to 1.8.0.
=> CLI:  update Azure.Identity dependency

.vsts-ci.yml
Resolve https://github.com/dotnet/sign/issues/488.
Enable [BinSkim](https://github.com/microsoft/binskim).
=> CLI:  enable BinSkim

.vsts-ci.yml
Resolve https://github.com/dotnet/sign/issues/488.
=> CLI: enable BinSkim

.vsts-ci.yml
Update YAML to build the main branch instead of the cli branch.
=> CLI: update YAML to build main branch

global.json
Resolve https://github.com/dotnet/sign/issues/517.
I _think_ this is the fix, based on https://github.com/dotnet/arcade/blob/2473ebd41195d623c82e351242d8cdc64bb3fd34/Documentation/ArcadeSdk.md#globaljson.
=> Update MSBuild version

docs/comparisons.md
=> Add documentation comparing NuGet and Sign CLI

docs/comparisons.md
@clairernovotny had some late feedback on this document.  This PR applies her feedback.
CC @aortiz-msft
=> Apply feedback

.vsts-ci.yml
Progress on https://github.com/dotnet/sign/issues/570.
This change is step 2 in https://github.com/dotnet/arcade/blob/3600aa80a01e90f38a7b86b9d7c1264e091aa5a8/Documentation/OneLocBuild.md#onboarding-to-onelocbuild-using-arcade.
=> Start enabling localization

docs/signing-tool-spec.md
Feedback that detection is a more precise term.
=> Update spec: "tamper resistance" -> "tamper detection"

.vsts-ci.yml
Progress on https://github.com/dotnet/sign/issues/570.
This change represents steps 6 and 7 in [OneLocBuild onboarding](https://github.com/dotnet/arcade/blob/b40fa37a9086f204fea57539ee19a47b45062295/Documentation/OneLocBuild.md).
=> Update localization job

src/Sign.Cli/xlf/Resources.cs.xlf, src/Sign.Cli/xlf/Resources.de.xlf, src/Sign.Cli/xlf/Resources.es.xlf, src/Sign.Cli/xlf/Resources.fr.xlf, src/Sign.Cli/xlf/Resources.it.xlf, src/Sign.Cli/xlf/Resources.ja.xlf, src/Sign.Cli/xlf/Resources.ko.xlf, src/Sign.Cli/xlf/Resources.pl.xlf, src/Sign.Cli/xlf/Resources.pt-BR.xlf, src/Sign.Cli/xlf/Resources.ru.xlf, src/Sign.Cli/xlf/Resources.tr.xlf, src/Sign.Cli/xlf/Resources.zh-Hans.xlf, src/Sign.Cli/xlf/Resources.zh-Hant.xlf
Resolve https://github.com/dotnet/sign/issues/601.
This change updates loc files that were changed by https://github.com/dotnet/sign/pull/600.
=> Update loc files

README.md, docs/azdo-build-and-sign.yml, docs/gh-build-and-sign.yml
=> Documentation & sample updates

src/Sign.Cli/CodeCommand.cs
Resolve https://github.com/dotnet/sign/issues/620.
=> Use resource string instead of hard-coded string

src/Sign.Core/Tools/OpenVsixSignTool.cs, test/Sign.Core.Test/Sign.Core.Test.csproj
This change removes some dead code.
=> Remove unused code

src/Sign.Core/Resources.resx, src/Sign.Core/xlf/Resources.cs.xlf, src/Sign.Core/xlf/Resources.de.xlf, src/Sign.Core/xlf/Resources.es.xlf, src/Sign.Core/xlf/Resources.fr.xlf, src/Sign.Core/xlf/Resources.it.xlf, src/Sign.Core/xlf/Resources.ja.xlf, src/Sign.Core/xlf/Resources.ko.xlf, src/Sign.Core/xlf/Resources.pl.xlf, src/Sign.Core/xlf/Resources.pt-BR.xlf, src/Sign.Core/xlf/Resources.ru.xlf, src/Sign.Core/xlf/Resources.tr.xlf, src/Sign.Core/xlf/Resources.zh-Hans.xlf, src/Sign.Core/xlf/Resources.zh-Hant.xlf
This PR adds a loc comment to a resource string modified by https://github.com/dotnet/sign/commit/a0c6bf75b13b33cba7170e13d477047d07fbfb02#diff-f0243fdd6fbbfb540457054900a66fd592aca55b3410d47e651313b479207b43R225.
=> Add resource string comment

.vsts-pr.yml
Progress on https://github.com/dotnet/sign/issues/676.
The PR copies /.vsts-ci.yml to ./.vsts-pr.yml then adds a comment to the top of each file indicating the AzDO pipeline URL.
=> CI:  create separate public PR YAML

eng/common/native/init-compiler.sh, eng/common/templates-official/job/job.yml, eng/common/templates-official/job/onelocbuild.yml, eng/common/templates-official/job/publish-build-assets.yml, eng/common/templates-official/job/source-build.yml, eng/common/templates-official/job/source-index-stage1.yml, eng/common/templates-official/post-build/post-build.yml, eng/common/templates-official/steps/component-governance.yml, eng/common/templates-official/variables/pool-providers.yml, eng/common/templates/job/source-index-stage1.yml, eng/common/templates/steps/component-governance.yml, global.json
Resolve https://github.com/dotnet/sign/issues/689.
This change copies latest changes from https://github.com/dotnet/arcade/tree/release/8.0.
CC @clairernovotny, @erdembayar
=> CI:  update Arcade to fix CI error 

src/Sign.Cli/AzureKeyVaultCommand.cs, test/Sign.SignatureProviders.KeyVault.Test/KeyVaultServiceProviderTests.cs, test/Sign.SignatureProviders.KeyVault.Test/KeyVaultServiceTests.cs
This PR corrects the names of the unit tests. And also some minor tweaks to the variables used in the unit tests. And I also just noticed that I left some unused usings in another PR.
=> Corrected the names of the unit tests.

global.json
Resolve https://github.com/dotnet/sign/issues/719.
Update the .NET SDK version in global.json.
=> Update .NET SDK version

src/Sign.Cli/PACKAGE.md, src/Sign.Cli/Sign.Cli.csproj
Resolve https://github.com/dotnet/sign/issues/631.
This change adds a simple package readme for NuGet.org.
=> Add package readme

.vsts-pr.yml
Resolve https://github.com/dotnet/sign/issues/751.
On failure, try to upload test results as an artifact.
=> CI:  upload test results on failure

eng/common/post-build/publish-using-darc.ps1, eng/common/sdl/NuGet.config, eng/common/sdl/execute-all-sdl-tools.ps1, eng/common/sdl/init-sdl.ps1, eng/common/sdl/sdl.ps1, eng/common/templates-official/job/publish-build-assets.yml, eng/common/templates-official/job/source-build.yml, eng/common/templates-official/job/source-index-stage1.yml, eng/common/templates-official/jobs/source-build.yml, eng/common/templates-official/post-build/post-build.yml, eng/common/templates-official/steps/enable-internal-runtimes.yml, eng/common/templates-official/steps/execute-sdl.yml, eng/common/templates-official/steps/get-delegation-sas.yml, eng/common/templates-official/steps/get-federated-access-token.yml, eng/common/templates/job/publish-build-assets.yml, eng/common/templates/job/source-build.yml, eng/common/templates/job/source-index-stage1.yml, eng/common/templates/jobs/source-build.yml, eng/common/templates/post-build/post-build.yml, eng/common/templates/post-build/setup-maestro-vars.yml, eng/common/templates/steps/enable-internal-runtimes.yml, eng/common/templates/steps/execute-sdl.yml, eng/common/templates/steps/get-delegation-sas.yml, eng/common/templates/steps/get-federated-access-token.yml, eng/common/templates/steps/telemetry-start.yml, eng/common/tools.ps1, global.json
Resolve https://github.com/dotnet/sign/issues/784.
This PR:
* Updates the /eng directory by mirroring https://github.com/dotnet/arcade/tree/release/8.0/eng into /eng
* Updates global.json to use the latest 8.x .NET SDK, runtime, and Arcade packages.
=> Update Arcade and .NET SDK

test/Sign.Core.Test/TestInfrastructure/Server/CertificateAuthority.cs
Resolve https://github.com/dotnet/sign/issues/796
See the Description in https://github.com/NuGet/NuGet.Client/pull/6103 for context.
Copied from https://github.com/NuGet/NuGet.Client/commit/8dbe10f0f2a023b5bfca8a6974f3016c79842ecd
=> Test:  remove SHA-1 verification from test OCSP responder

src/Sign.Cli/AzureKeyVaultCommand.cs
=> Added missing registration for the AzureKeyVaultCommand and removed unused KeyClient.

.config/1espt/PipelineAutobaseliningConfig.yml
Resolve https://github.com/dotnet/sign/issues/832.
This is a manual port of an auto-generated branch in the internal repo.
=> CI:  update baselines for SDL tooling

README.md
Resolve https://github.com/dotnet/sign/issues/804
=> Documentation:  document Azure Key Vault RBAC roles

test/Sign.Core.Test/TestInfrastructure/Server/TimestampService.cs, test/Sign.Core.Test/Tools/VSIXSignTool/Crypt32Tests.cs
Progress on https://github.com/dotnet/sign/issues/671.
=> Test:  improve test diagnostics

src/Sign.Cli/PACKAGE.md
Resolve https://github.com/dotnet/sign/issues/857
=> Update package readme

global.json
Resolve https://github.com/dotnet/sign/issues/859.
=> Update .NET SDK and runtime

docs/file-globbing.md
Added documentation and examples for file list filtering and globbing.
Fixes #783
=> Add documentation for file filtering/globbing

Directory.Packages.props, global.json
Resolve https://github.com/dotnet/sign/issues/913.
=> Update .NET SDK, runtime, and dependencies
